# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/margaretpeterson/Desktop/raspiCamera

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/margaretpeterson/Desktop/raspiCamera

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/margaretpeterson/Desktop/raspiCamera/CMakeFiles /Users/margaretpeterson/Desktop/raspiCamera/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/margaretpeterson/Desktop/raspiCamera/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named opencv_cam_server

# Build rule for target.
opencv_cam_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opencv_cam_server
.PHONY : opencv_cam_server

# fast build rule for target.
opencv_cam_server/fast:
	$(MAKE) -f CMakeFiles/opencv_cam_server.dir/build.make CMakeFiles/opencv_cam_server.dir/build
.PHONY : opencv_cam_server/fast

Metrics.o: Metrics.cpp.o

.PHONY : Metrics.o

# target to build an object file
Metrics.cpp.o:
	$(MAKE) -f CMakeFiles/opencv_cam_server.dir/build.make CMakeFiles/opencv_cam_server.dir/Metrics.cpp.o
.PHONY : Metrics.cpp.o

Metrics.i: Metrics.cpp.i

.PHONY : Metrics.i

# target to preprocess a source file
Metrics.cpp.i:
	$(MAKE) -f CMakeFiles/opencv_cam_server.dir/build.make CMakeFiles/opencv_cam_server.dir/Metrics.cpp.i
.PHONY : Metrics.cpp.i

Metrics.s: Metrics.cpp.s

.PHONY : Metrics.s

# target to generate assembly for a file
Metrics.cpp.s:
	$(MAKE) -f CMakeFiles/opencv_cam_server.dir/build.make CMakeFiles/opencv_cam_server.dir/Metrics.cpp.s
.PHONY : Metrics.cpp.s

OpenFilter.o: OpenFilter.cpp.o

.PHONY : OpenFilter.o

# target to build an object file
OpenFilter.cpp.o:
	$(MAKE) -f CMakeFiles/opencv_cam_server.dir/build.make CMakeFiles/opencv_cam_server.dir/OpenFilter.cpp.o
.PHONY : OpenFilter.cpp.o

OpenFilter.i: OpenFilter.cpp.i

.PHONY : OpenFilter.i

# target to preprocess a source file
OpenFilter.cpp.i:
	$(MAKE) -f CMakeFiles/opencv_cam_server.dir/build.make CMakeFiles/opencv_cam_server.dir/OpenFilter.cpp.i
.PHONY : OpenFilter.cpp.i

OpenFilter.s: OpenFilter.cpp.s

.PHONY : OpenFilter.s

# target to generate assembly for a file
OpenFilter.cpp.s:
	$(MAKE) -f CMakeFiles/opencv_cam_server.dir/build.make CMakeFiles/opencv_cam_server.dir/OpenFilter.cpp.s
.PHONY : OpenFilter.cpp.s

OpenVideo.o: OpenVideo.cpp.o

.PHONY : OpenVideo.o

# target to build an object file
OpenVideo.cpp.o:
	$(MAKE) -f CMakeFiles/opencv_cam_server.dir/build.make CMakeFiles/opencv_cam_server.dir/OpenVideo.cpp.o
.PHONY : OpenVideo.cpp.o

OpenVideo.i: OpenVideo.cpp.i

.PHONY : OpenVideo.i

# target to preprocess a source file
OpenVideo.cpp.i:
	$(MAKE) -f CMakeFiles/opencv_cam_server.dir/build.make CMakeFiles/opencv_cam_server.dir/OpenVideo.cpp.i
.PHONY : OpenVideo.cpp.i

OpenVideo.s: OpenVideo.cpp.s

.PHONY : OpenVideo.s

# target to generate assembly for a file
OpenVideo.cpp.s:
	$(MAKE) -f CMakeFiles/opencv_cam_server.dir/build.make CMakeFiles/opencv_cam_server.dir/OpenVideo.cpp.s
.PHONY : OpenVideo.cpp.s

cameraServer.o: cameraServer.cpp.o

.PHONY : cameraServer.o

# target to build an object file
cameraServer.cpp.o:
	$(MAKE) -f CMakeFiles/opencv_cam_server.dir/build.make CMakeFiles/opencv_cam_server.dir/cameraServer.cpp.o
.PHONY : cameraServer.cpp.o

cameraServer.i: cameraServer.cpp.i

.PHONY : cameraServer.i

# target to preprocess a source file
cameraServer.cpp.i:
	$(MAKE) -f CMakeFiles/opencv_cam_server.dir/build.make CMakeFiles/opencv_cam_server.dir/cameraServer.cpp.i
.PHONY : cameraServer.cpp.i

cameraServer.s: cameraServer.cpp.s

.PHONY : cameraServer.s

# target to generate assembly for a file
cameraServer.cpp.s:
	$(MAKE) -f CMakeFiles/opencv_cam_server.dir/build.make CMakeFiles/opencv_cam_server.dir/cameraServer.cpp.s
.PHONY : cameraServer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... opencv_cam_server"
	@echo "... Metrics.o"
	@echo "... Metrics.i"
	@echo "... Metrics.s"
	@echo "... OpenFilter.o"
	@echo "... OpenFilter.i"
	@echo "... OpenFilter.s"
	@echo "... OpenVideo.o"
	@echo "... OpenVideo.i"
	@echo "... OpenVideo.s"
	@echo "... cameraServer.o"
	@echo "... cameraServer.i"
	@echo "... cameraServer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

